CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Equipment" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Category" text NOT NULL,
    "StatusEquipment" integer NOT NULL,
    CONSTRAINT "PK_Equipment" PRIMARY KEY ("Id")
);

CREATE TABLE "Student" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    CONSTRAINT "PK_Student" PRIMARY KEY ("Id")
);

CREATE TABLE "Loan" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StudentId" integer NOT NULL,
    "EquipmentId" integer NOT NULL,
    "LoanDate" timestamp with time zone NOT NULL,
    "_expectedReturnDate" timestamp with time zone NOT NULL,
    "ExpectedReturnDate" timestamp with time zone NOT NULL,
    "ActualReturnDate" timestamp with time zone,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Loan" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Loan_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Loan_Student_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Student" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Loan_EquipmentId" ON "Loan" ("EquipmentId");

CREATE INDEX "IX_Loan_StudentId" ON "Loan" ("StudentId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260730195349_InitialCreate', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE "Loan" ALTER COLUMN "StudentId" DROP NOT NULL;

ALTER TABLE "Loan" ALTER COLUMN "EquipmentId" DROP NOT NULL;

CREATE UNIQUE INDEX "IX_Student_Email" ON "Student" ("Email");

CREATE UNIQUE INDEX "IX_Equipment_Name" ON "Equipment" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260730211934_InitialCreatev1', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE "Loan" DROP COLUMN "_expectedReturnDate";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260731222614_RemoveExtraExpectedColumn', '10.0.10');

COMMIT;

